### ISSUE TITLE
autocompletion tooltip flashes, likely due to autocompletion conflicts

### ISSUE THREAD

**Issue by hackape** [tptee/FlowIDE#6]
Autocompletion tooltip flashes, briefly shows a batch of options, then quickly gets override by another batch provided by flow. I guess it's due to conflict with sublime's stock autocompletion. Can you provide a solution to disable fix behavior?

Did google but find no good solution. I know this is not a problem of FlowIDE itself, but still think here's the right place to ask, cus other users are very likely to encounter the same problem.

**Comment by dclowd9901** [comment]
Yep, having this issue as well. Can't use FlowIDE because of it.

**Comment by yanndinendal** [comment]
I think it's fixed with the `show_sublime_autocomplete_suggestions: true` option of FlowIDE 1.2.0?

**Comment by janpaul123** [comment]
I still have this issue, even with `show_sublime_autocomplete_suggestions` set to false (which seems to be the default now.
